import {
  IconAdjustmentsAlt,
  IconArrowNarrowRight,
  IconBaselineDensityMedium,
  IconBell,
  IconCalendarMonth,
  IconLayoutGrid,
  IconLogout2,
  IconMessage,
  IconMovie,
  IconSearch,
  IconThumbUp,
  IconUser,
  IconSettings,
} from 'angular-tabler-icons/icons';

export const icons = {
  IconBell,
  IconMessage,
  IconUser,
  IconLogout2,
  IconArrowNarrowRight,
  IconMovie,
  IconLayoutGrid,
  IconBaselineDensityMedium,
  IconThumbUp,
  IconCalendarMonth,
  IconSearch,
  IconAdjustmentsAlt,
  IconSettings,
};
